apiVersion: v1
kind: ConfigMap
metadata:
  name: radius-raddb-overwrites
  namespace: ${AppNS}
data:
  test-only: |
    #Test-File.
    #
  authorize: |
    #
    #  Configuration file for the rlm_files module.
    #  Please see rlm_files(5) manpage for more information.
    #
    #  This file contains authentication security and configuration
    #  information for each user.  Accounting requests are NOT processed
    #  through this file.  Instead, see 'accounting', in this directory.
    #
    #  The first field is the user's name and can be up to
    #  253 characters in length.  This is followed (on the same line) with
    #  the list of authentication requirements for that user.  This can
    #  include password, comm server name, comm server port number, protocol
    #  type (perhaps set by the "hints" file), and huntgroup name (set by
    #  the "huntgroups" file).
    #
    #  If you are not sure why a particular reply is being sent by the
    #  server, then run the server in debugging mode (radiusd -X), and
    #  you will see which entries in this file are matched.
    #
    #  When an authentication request is received from the comm server,
    #  these values are tested. Only the first match is used unless the
    #  "Fall-Through" variable is set to "Yes".
    #
    #  A special user named "DEFAULT" matches on all usernames.
    #  You can have several DEFAULT entries. All entries are processed
    #  in the order they appear in this file. The first entry that
    #  matches the login-request will stop processing unless you use
    #  the Fall-Through variable.
    #
    #  Indented (with the tab character) lines following the first
    #  line indicate the configuration values to be passed back to
    #  the comm server to allow the initiation of a user session.
    #  This can include things like the PPP configuration values
    #  or the host to log the user onto.
    #
    #  You can include another `users' file with `$INCLUDE users.other'
    
    #
    #  For a list of RADIUS attributes, and links to their definitions,
    #  see: http://www.freeradius.org/rfc/attributes.html
    #
    #  Entries below this point are examples included in the server for
    #  educational purposes. They may be deleted from the deployed
    #  configuration without impacting the operation of the server.
    #
    
    #
    # Deny access for a specific user.  Note that this entry MUST
    # be before any other 'Auth-Type' attribute which results in the user
    # being authenticated.
    #
    # Note that there is NO 'Fall-Through' attribute, so the user will not
    # be given any additional resources.
    #
    #lameuser    Auth-Type := Reject
    #    Reply-Message = "Your account has been disabled."
    
    #
    # Deny access for a group of users.
    #
    # Note that there is NO 'Fall-Through' attribute, so the user will not
    # be given any additional resources.
    #
    #DEFAULT    Group == "disabled", Auth-Type := Reject
    #    Reply-Message = "Your account has been disabled."
    #
    
    #
    # This is a complete entry for "steve". Note that there is no Fall-Through
    # entry so that no DEFAULT entry will be used, and the user will NOT
    # get any attributes in addition to the ones listed here.
    #
    #steve    Cleartext-Password := "testing"
    #  Service-Type = Framed-User,
    #  Framed-Protocol = PPP,
    #  Framed-IP-Address = 172.16.3.33,
    #  Framed-IP-Netmask = 255.255.255.0,
    #  Framed-Routing = Broadcast-Listen,
    #  Framed-Filter-Id = "std.ppp",
    #  Framed-MTU = 1500,
    #  Framed-Compression = Van-Jacobsen-TCP-IP
    
    TestUser1  Cleartext-Password := "testing"
           Service-Type = Framed-User,
           Framed-Protocol = PPP  #,
    #       Framed-IP-Address = 172.16.3.33,
    #       Framed-IP-Netmask = 255.255.255.0,
    #       Framed-Routing = Broadcast-Listen,
    #       Framed-Filter-Id = "std.ppp",
    #       Framed-MTU = 1500,
    #       Framed-Compression = Van-Jacobsen-TCP-IP
    
    TestUser2  Cleartext-Password := "DemoPwd4SecureStr!ng"
           Service-Type = Framed-User,
           Framed-Protocol = PPP
    
    #
    # If the user logs in as 'username.shell', then authenticate them
    # using the default method, give them shell access, and stop processing
    # the rest of the file.
    #
    #DEFAULT    Suffix == ".shell"
    #    Service-Type = Login-User,
    #    Login-Service = Telnet,
    #    Login-IP-Host = your.shell.machine
    
    
    #
    # The rest of this file contains the several DEFAULT entries.
    # DEFAULT entries match with all login names.
    # Note that DEFAULT entries can also Fall-Through (see first entry).
    # A name-value pair from a DEFAULT entry will _NEVER_ override
    # an already existing name-value pair.
    #
    
    # Sample defaults for all framed connections.
    #
    #DEFAULT   Service-Type == Framed-User
    #  Framed-IP-Address = 255.255.255.254,
    #  Framed-MTU = 576,
    #  Service-Type = Framed-User,
    #  Fall-Through = Yes
    
    #
    # Default for PPP: dynamic IP address, PPP mode, VJ-compression.
    # NOTE: we do not use Hint = "PPP", since PPP might also be auto-detected
    #	by the terminal server in which case there may not be a "P" suffix.
    #	The terminal server sends "Framed-Protocol = PPP" for auto PPP.
    #
    DEFAULT	Framed-Protocol == PPP
      Framed-Protocol = PPP,
      Framed-Compression = Van-Jacobson-TCP-IP
    
    #
    # Default for CSLIP: dynamic IP address, SLIP mode, VJ-compression.
    #
    DEFAULT	Hint == "CSLIP"
      Framed-Protocol = SLIP,
      Framed-Compression = Van-Jacobson-TCP-IP
    
    #
    # Default for SLIP: dynamic IP address, SLIP mode.
    #
    DEFAULT	Hint == "SLIP"
      Framed-Protocol = SLIP
    
    #
    # Last default: rlogin to our main server.
    #
    #DEFAULT
    #  Service-Type = Login-User,
    #  Login-Service = Rlogin,
    #  Login-IP-Host = shellbox.ispdomain.com
    
    # #
    # # Last default: shell on the local terminal server.
    # #
    # DEFAULT
    #   Service-Type = Administrative-User
    
    # On no match, the user is denied access.
    #########################################################
    # You should add test accounts to the TOP of this file! #
    # See the example user "bob" above.                     #
    #########################################################
