---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radius
  namespace: ${AppNS}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radius
  template:
    metadata:
      labels:
        app: radius
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - radius
            topologyKey: kubernetes.io/hostname
      volumes:
        - name: etc-raddb
          emptyDir:
            sizeLimit: 500Mi
        - name: raddb-overwrites
          configMap:
            name: radius-raddb-overwrites
            optional: true
            items:
            #Define her your freeradius-config-files
            # each must be defined in the ConfigMap: cm-radius-raddb-overwrites.yaml
            - key: "authorize"
              path: "mods-config/files/authorize"
            #- key: "user-interface.properties"
            #  path: "user-interface.properties"
        #- name: etc-raddb
        #  persistentVolumeClaim:
        #     claimName: pvc-freeradius-raddb
        #- name: raddb-secrets
        #  secret:
        #    secretName: freeradius-secrets
      containers:
      - image: eherzog/freeradius:0.0.1
        name: radius
        imagePullPolicy: IfNotPresent
        env:
        - name: PSQL_HOST
          value: "${DBHOST}"
        - name: PSQL_USER
          value: "${DBUSER}"
        - name: PSQL_PASSWORD
          value: "${DBPWD}"
        - name: PSQL_DATABASE
          value: "${DBNAME}"
        - name: PSQL_PORT
          value: "5432"
        - name: TZ
          value: "Europe/Vienna"
        volumeMounts:
          - name: etc-raddb
            mountPath: "/etc/raddb"
          - name: raddb-overwrites
            mountPath: "/raddb-overwrites"
---
