---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radius
  namespace: ${AppNS}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radius
  template:
    metadata:
      labels:
        app: radius
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - radius
            topologyKey: kubernetes.io/hostname
      ###
      ### With SCC for OKD/OpenShift
      #securityContext: {}
      #serviceAccount: sa-radius
      #serviceAccountName: sa-radius
      ###
      volumes:
        - name: etc-raddb
          emptyDir:
            sizeLimit: 500Mi
        - name: raddb-overwrites
          configMap:
            defaultMode: 438
            name: radius-raddb-overwrites
            optional: true
        #- name: etc-raddb
        #  persistentVolumeClaim:
        #     claimName: pvc-freeradius-raddb
        #- name: raddb-secrets
        #  secret:
        #    secretName: freeradius-secrets
      containers:
      - image: eherzog/freeradius:0.0.1
        name: radius
        imagePullPolicy: IfNotPresent
        env:
        - name: RAD_DEBUG
          value: "no"
        - name: TZ
          value: "Europe/Vienna"
        - name: LINKS_REMOVE
          value: ""  #mods-enabled/dhcp;mods-enabled/sql
        - name: LINKS_ADD
          value: "" #mods-available/dhcp,mods-enabled/dhcp;mods-available/sql,mods-enabled/sql
        volumeMounts:
          - name: etc-raddb
            mountPath: "/etc/raddb"
          - name: raddb-overwrites
            mountPath: "/raddb-overwrites"
---
