---
apiVersion: v1
kind: Service
metadata:
  name: svc-web
  namespace: ${AppNS}
spec:
  #externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: radius1812
    port: 1812
    protocol: UDP
    targetPort: 1812
  - name: radius1813
    port: 1813
    protocol: UDP
    targetPort: 1813
  selector:
    app: radius
---
