---
apiVersion: v1
kind: Service
metadata:
  name: svc-radius-web
  namespace: ${AppNS}
spec:
  #externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: radius-web
---
